In [1]:
import pandas as pd
import os

In [3]:
cv_results_df = pd.read_csv("outputs/cross_validation_results.csv")

In [4]:
cv_results_df

,Objective,Training Accuracy Mean,Training Accuracy STD,Validation Accuracy Mean,Validation Accuracy STD,Recall Mean,Recall STD,Precision Mean,Precision STD,Final Train Accuracy,Test Accuracy,Final Recall,Final Precision,Seed
0,triplet,0.994880,0.002039,0.943541,0.005580,0.946424,0.007758,0.943541,0.005580,0.996364,0.939655,0.940334,0.939655,2596
1,deepsad,0.907286,0.008082,0.888999,0.019951,0.903842,0.005613,0.888999,0.019951,0.895228,0.898964,0.923666,0.898964,2596
2,hsad,0.797849,0.013044,0.726683,0.022773,0.782414,0.038324,0.726683,0.022773,0.811722,0.722798,0.775139,0.722798,2596
3,final,0.995598,0.000558,0.946220,0.003282,0.948656,0.004411,0.946220,0.003282,0.995981,0.950192,0.952836,0.950192,2596
4,triplet,0.996077,0.000719,0.944306,0.003750,0.946291,0.004148,0.944306,0.003750,0.994258,0.942529,0.944696,0.942529,3645
5,deepsad,0.907935,0.008180,0.889003,0.013655,0.893018,0.015001,0.889003,0.013655,0.908714,0.870466,0.872499,0.870466,3645
6,hsad,0.797458,0.010988,0.722012,0.034453,0.734503,0.033350,0.722012,0.034453,0.808091,0.730570,0.737340,0.730570,3645
7,final,0.995407,0.001085,0.948134,0.005973,0.949051,0.005847,0.948134,0.005973,0.996364,0.947318,0.949870,0.947318,3645
8,triplet,0.995742,0.000412,0.945455,0.005064,0.947838,0.005633,0.945455,0.005064,0.988325,0.942529,0.948988,0.942529,4586
9,deepsad,0.915714,0.005412,0.901981,0.016378,0.906726,0.017497,0.901981,0.016378,0.923755,0.911917,0.918299,0.911917,4586
10,hsad,0.806538,0.017132,0.737559,0.014101,0.768591,0.034017,0.737559,0.014101,0.817427,0.727979,0.743722,0.727979,4586
11,final,0.996077,0.002127,0.942966,0.007646,0.943734,0.008631,0.942967,0.007646,0.995407,0.946360,0.948766,0.946360,4586

In [5]:
cv_results_df.groupby("Objective").mean()

,Training Accuracy Mean,Training Accuracy STD,Validation Accuracy Mean,Validation Accuracy STD,Recall Mean,Recall STD,Precision Mean,Precision STD,Final Train Accuracy,Test Accuracy,Final Recall,Final Precision,Seed
Objective,,,,,,,,,,,,,
deepsad,0.910312,0.007225,0.893328,0.016661,0.901195,0.012703,0.893328,0.016661,0.909232,0.893782,0.904821,0.893782,3609.0
final,0.995694,0.001257,0.945774,0.005634,0.947147,0.006296,0.945774,0.005634,0.995917,0.947957,0.950491,0.947957,3609.0
hsad,0.800615,0.013722,0.728751,0.023776,0.761836,0.035230,0.728751,0.023776,0.812414,0.727116,0.752067,0.727116,3609.0
triplet,0.995566,0.001057,0.944434,0.004798,0.946851,0.005847,0.944434,0.004798,0.992982,0.941571,0.944672,0.941571,3609.0