In [1]:
import pandas as pd
import os

In [2]:
cv_results_df = pd.read_csv("outputs/cross_validation_results.csv")

In [3]:
cv_results_df

,Objective,Training Accuracy Mean,Training Accuracy STD,Validation Accuracy Mean,Validation Accuracy STD,Recall Mean,Recall STD,Precision Mean,Precision STD,Final Train Accuracy,Test Accuracy,Final Recall,Final Precision,Seed
0,triplet,0.997807,0.001124,0.927241,0.006654,0.929459,0.008988,0.927241,0.006654,0.997420,0.901809,0.899295,0.901809,3857184236
1,deepsad,0.934261,0.010535,0.911301,0.023893,0.921715,0.016602,0.911301,0.023893,0.936203,0.906736,0.912034,0.906736,47024940
2,hsad,0.742733,0.026832,0.714245,0.032738,0.758534,0.044275,0.714245,0.032738,0.766079,0.733161,0.783394,0.733161,454078783
3,triplet,0.996389,0.003838,0.924654,0.010944,0.925264,0.013714,0.924654,0.010944,0.995356,0.901809,0.899295,0.901809,3957578021
4,deepsad,0.938667,0.006831,0.916496,0.015850,0.919486,0.013977,0.916496,0.015850,0.933091,0.898964,0.899094,0.898964,221195306
5,hsad,0.722250,0.028576,0.684137,0.023523,0.742067,0.063840,0.684137,0.023523,0.711100,0.689119,0.716299,0.689119,1900869660
6,triplet,0.998710,0.000816,0.925170,0.015721,0.926440,0.018195,0.925170,0.015721,0.998452,0.896641,0.894508,0.896641,901686740
7,deepsad,0.936851,0.003127,0.911831,0.014728,0.917286,0.012808,0.911831,0.014728,0.918050,0.893782,0.911928,0.893782,1964295182
8,hsad,0.679080,0.054885,0.651962,0.051940,0.775674,0.067131,0.651962,0.051940,0.709544,0.678756,0.841944,0.678756,31126200
9,triplet,0.997807,0.000966,0.926206,0.008939,0.928407,0.011600,0.926206,0.008939,0.998452,0.896641,0.895231,0.896641,2034018468
10,deepsad,0.934776,0.006085,0.909238,0.012469,0.915205,0.009808,0.909238,0.012469,0.920643,0.893782,0.907934,0.893782,214383761
11,hsad,0.720177,0.024867,0.691381,0.025179,0.823050,0.031732,0.691381,0.025179,0.771784,0.725389,0.743062,0.725389,3308405860
12,triplet,0.998581,0.000856,0.926726,0.010288,0.927779,0.011206,0.926726,0.010288,0.997420,0.904393,0.902346,0.904393,1570683339
13,deepsad,0.929331,0.004511,0.898342,0.021368,0.911327,0.011837,0.898342,0.021368,0.924793,0.896373,0.907739,0.896373,1500785577
14,hsad,0.749487,0.022376,0.709532,0.016606,0.758408,0.049582,0.709532,0.016606,0.767635,0.725389,0.747287,0.725389,172356980

In [4]:
cv_results_df.groupby('Objective').mean()

,Training Accuracy Mean,Training Accuracy STD,Validation Accuracy Mean,Validation Accuracy STD,Recall Mean,Recall STD,Precision Mean,Precision STD,Final Train Accuracy,Test Accuracy,Final Recall,Final Precision,Seed
Objective,,,,,,,,,,,,,
deepsad,0.934777,0.006218,0.909441,0.017662,0.917004,0.013006,0.909441,0.017662,0.926556,0.897927,0.907746,0.897927,7.895370e+08
hsad,0.722746,0.031508,0.690252,0.029997,0.771547,0.051312,0.690252,0.029997,0.745228,0.710363,0.766397,0.710363,1.173367e+09
triplet,0.997859,0.001520,0.925999,0.010509,0.927470,0.012741,0.925999,0.010509,0.997420,0.900258,0.898135,0.900258,2.464230e+09

In [5]:
cv_results_df.groupby("Objective").mean()

,Training Accuracy Mean,Training Accuracy STD,Validation Accuracy Mean,Validation Accuracy STD,Recall Mean,Recall STD,Precision Mean,Precision STD,Final Train Accuracy,Test Accuracy,Final Recall,Final Precision,Seed
Objective,,,,,,,,,,,,,
deepsad,0.910312,0.007225,0.893328,0.016661,0.901195,0.012703,0.893328,0.016661,0.909232,0.893782,0.904821,0.893782,3609.0
final,0.995694,0.001257,0.945774,0.005634,0.947147,0.006296,0.945774,0.005634,0.995917,0.947957,0.950491,0.947957,3609.0
hsad,0.800615,0.013722,0.728751,0.023776,0.761836,0.035230,0.728751,0.023776,0.812414,0.727116,0.752067,0.727116,3609.0
triplet,0.995566,0.001057,0.944434,0.004798,0.946851,0.005847,0.944434,0.004798,0.992982,0.941571,0.944672,0.941571,3609.0